apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-python-weather-mcp
  labels:
    app: ai-python-weather-mcp
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: ai-python-weather-mcp

  template:
    metadata:
      labels:
        app: ai-python-weather-mcp

    spec:
      containers:
        - name: ai-python-weather-mcp

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP

          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment.ENVIRONMENT | quote }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            {{- toYaml .Values.resources | nindent 12 }}