apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-mcp

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: weather-mcp

  template:
    metadata:
      labels:
        app: weather-mcp

    spec:
      containers:
        - name: weather-mcp

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP

          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment.ENVIRONMENT | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}

            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}