apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-helm-config-service

spec:
  selector:
    app: helm-config

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}